config/routes.rb
Rails.application.routes.draw do

  root 'cocktails#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Un utilisateur peut voir la liste des cocktails
  # Un utilisateur peut voir les détails d'un cocktail donné, avec la dose nécessaire pour chaque ingrédient
  # Un utilisateur peut créer un nouveau cocktail
  get 'pages/about'

  resources :cocktails, only: [:show, :new, :create] do
    resources :doses, only: [:new, :create]
  end

  delete "doses/:id", to: "doses#destroy", as: "dose"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence:true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    cocktail = Cocktail.new(cocktail_params)
    if cocktail.save
      redirect_to cocktail
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :image_url, :photo)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to @cocktail , notice: "Recette ajoutée"
    else
      render :new, notice: "Attention, l'ingredient est deja dans le cocktai"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to @dose.cocktail, notice: "La dose à été supprimée"
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_picture(cocktail)
     if cocktail.photo.attached?
      cl_image_tag cocktail.photo.key, class:"img-fluid"
     else
      image_tag 'chicandier.jpg'
     end
  end
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :photo, as: :file %>
  <%= f.input :name %>
  <%= f.submit "Créer un cocktail" %>
<% end %>

app/views/cocktails/index.html.erb
<h2>Chercher un cocktail dans la liste</h2>
<div id="container">
    <div class="panel-block">
        <input type="text" id="search" class="form-control" placeholder="Nom du cocktail... (ex: margarita)">
    </div>

      <div class="cards" id="results" >
      </div>

    <div class="panel-block mt-2">
      <button id="reset" class="btn btn-primary">
        Effacer la recherche
      </button>
    </div>
</div>

<hr>

<h2>Tous les cocktails</h2>


<div class="row row-cols-1 row-cols-md-3">
  <% @cocktails.each do |cocktail| %>
  <div class="col">
    <div class="card" style="width: 18rem;">
      <%= display_picture(cocktail) %>
      <div class="card-body">
        <h5 class="card-title"><%= cocktail.name %></h5>
        <%= link_to 'Voir', cocktail, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<h1>Créer un cocktail</h1>
<%= render "form" %>

app/views/cocktails/show.html.erb
<div class="row">
  <div class="col-4">
    <div class="card" style="width: 20rem;">
      <div class="card-body">
        <h1 class="card-title"><%= @cocktail.name %></h1>
          <% @cocktail.doses.each do |dose| %>
          <div class="d-flex align-items-center mt-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cup-straw text-primary mr-2" viewBox="0 0 16 16">
              <path d="M13.902.334a.5.5 0 0 1-.28.65l-2.254.902-.4 1.927c.376.095.715.215.972.367.228.135.56.396.56.82 0 .046-.004.09-.011.132l-.962 9.068a1.28 1.28 0 0 1-.524.93c-.488.34-1.494.87-3.01.87-1.516 0-2.522-.53-3.01-.87a1.28 1.28 0 0 1-.524-.93L3.51 5.132A.78.78 0 0 1 3.5 5c0-.424.332-.685.56-.82.262-.154.607-.276.99-.372C5.824 3.614 6.867 3.5 8 3.5c.712 0 1.389.045 1.985.127l.464-2.215a.5.5 0 0 1 .303-.356l2.5-1a.5.5 0 0 1 .65.278zM9.768 4.607A13.991 13.991 0 0 0 8 4.5c-1.076 0-2.033.11-2.707.278A3.284 3.284 0 0 0 4.645 5c.146.073.362.15.648.222C5.967 5.39 6.924 5.5 8 5.5c.571 0 1.109-.03 1.588-.085l.18-.808zm.292 1.756C9.445 6.45 8.742 6.5 8 6.5c-1.133 0-2.176-.114-2.95-.308a5.514 5.514 0 0 1-.435-.127l.838 8.03c.013.121.06.186.102.215.357.249 1.168.69 2.438.69 1.27 0 2.081-.441 2.438-.69.042-.029.09-.094.102-.215l.852-8.03a5.517 5.517 0 0 1-.435.127 8.88 8.88 0 0 1-.89.17zM4.467 4.884s.003.002.005.006l-.005-.006zm7.066 0l-.005.006c.002-.004.005-.006.005-.006zM11.354 5a3.174 3.174 0 0 0-.604-.21l-.099.445.055-.013c.286-.072.502-.149.648-.222z"/>
            </svg>
            <h4 class="card-text"><%= dose.ingredient.name %></h4>
          </div>

            <div class="dose">
                <div class="d-flex mt-2 mb-2 justify-content-between border-bottom">
                  <p class="card-text"><%= dose.description %></p>
                  <%= link_to 'x', dose_path(dose), method: :delete, class:"font-weight-bold text-danger" %>
                </div>
            </div>
          <% end %>
      </div>
      <div class="d-flex align-items-center mb-3">
        <div class="col-8">
          <%= link_to 'Ajouter une dose', new_cocktail_dose_path(@cocktail), class:"btn btn-outline-primary" %>
        </div>
      </div>
    </div>
    <div class="card mt-2 p-2" style="width: 20rem;">
      <%= link_to 'Revenir', root_path%>
    </div>
  </div>

  <div class="col-8">
    <%= display_picture(@cocktail) %>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient  %>
  <%= f.submit %>
<% end %>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<%= render "form" %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-lewagon mb-3">
  <a class="navbar-brand d-flex " href="/">
    <%= image_tag "logo-bleu-metal.png", class: "d-inline-block align-top" %>
    <h3 class="ml-3">Bleu Metal !</h3>
  </a>
  <%= link_to 'Ajouter un cocktail', new_cocktail_path , class: "btn btn-primary my-2 my-sm-0" %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paaam !</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

<p>
  On s'est battu pour ça, j'veux dire on a fait des révolutions, nos grands parents se sont beurrés la gueule le Vendredi midi, nos parents se sont beurrés la gueule le Vendredi après-midi, personne ne doit travailler le Vendredi après-midi. Le Vendredi après-midi on est Bleu on dit des conneries, on insultes des gens, on dort aux chiottes, on ne bosse pas et on ne prend pas de rendez-vous le Vendredi après-midi, on est pas des allemands, MERDE !
</p>